[font]
size = 12.5
offset.y = 4
glyph_offset.y = 2

[font.normal]
family = "ComicCode Nerd Font"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[shell]
args = ["-l", "-c", "tmux new-session -A -s base"]
program = "/bin/zsh"

[window]
decorations = "none"
opacity = 0.95

[window.dimensions]
columns = 200
lines = 64

[window.padding]
x = 8
y = 8
